version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: '11:00'
    timezone: Japan
  labels:
  - "CI/CD"
  commit-message:
    prefix: ci
